In [2]:
from settingDatetime import *
import FinanceDataReader as fdr
import pandas as pd

In [3]:
"""
stocklist = fdr.StockListing('KRX') #나중에 stocklist 변경하기
stocks = pd.concat([stocklist.Name, stocklist.Symbol], axis = 1)

tic = "".join(list(stocks[stocks.Name=='삼성전자'].Symbol.values))
print(tic)
df = fdr.DataReader(tic,yesterday_default,yesterday_default)
print(df.Change.values)
"""

'\nstocklist = fdr.StockListing(\'KRX\') #나중에 stocklist 변경하기\nstocks = pd.concat([stocklist.Name, stocklist.Symbol], axis = 1)\n\ntic = "".join(list(stocks[stocks.Name==\'삼성전자\'].Symbol.values))\nprint(tic)\ndf = fdr.DataReader(tic,yesterday_default,yesterday_default)\nprint(df.Change.values)\n'

In [4]:
fdr.DataReader('005930','2022-03-21', '2022-03-28')

             Open   High    Low  Close    Volume    Change
Date
2022-03-21  70900  71000  69900  69900  11169002 -0.011315
2022-03-22  69900  70500  69900  70300   9402666  0.005722
2022-03-23  70600  71200  70300  70500  12398025  0.002845
2022-03-24  69600  70300  69600  69800  37943357 -0.009929
2022-03-25  70100  70200  69600  69800  12986010  0.000000
2022-03-28  69500  69900  69200  69700  12534621 -0.001433

In [5]:
stocklist = fdr.StockListing('KRX') #나중에 stocklist 변경하기
stocks = pd.concat([stocklist.Name, stocklist.Symbol], axis = 1)

#rank = pd.read_csv(f'./data/rank/{target}_rank.csv',encoding='utf-8-sig')
#companylist = list(rank.word)
#answer = pd.DataFrame({'word':companylist})

companylist = ['삼성전자','NAVER','카카오','LG에너지솔루션','SK하이닉스','삼성바이오로직스','삼성SDI', '현대차', 'LG화학','기아']
answer = pd.DataFrame({'date':target, 'day':target_day,'word':companylist})
changelst = []

for element in companylist:
    tic = "".join(list(stocks[stocks.Name==element].Symbol.values))
    df = fdr.DataReader(tic,target_default,target_default)
    #print(df.Change.values)
    if df.Change.values>0:
        changelst.append('up')
    elif df.Change.values==0:
        changelst.append('stay')
    elif df.Change.values.any()==False:
        changelst.append('-')
    else:
        changelst.append('down')

answer['change'] = changelst
answer.to_csv(f'./data/answer/{target}_answer.csv',encoding='utf-8-sig',index=False)

display(answer)

                date    day      word change
0  20220325-20220327  금,토,일      삼성전자   stay
1  20220325-20220327  금,토,일     NAVER   down
2  20220325-20220327  금,토,일       카카오   stay
3  20220325-20220327  금,토,일  LG에너지솔루션     up
4  20220325-20220327  금,토,일    SK하이닉스   down
5  20220325-20220327  금,토,일  삼성바이오로직스   down
6  20220325-20220327  금,토,일     삼성SDI     up
7  20220325-20220327  금,토,일       현대차   down
8  20220325-20220327  금,토,일      LG화학   down
9  20220325-20220327  금,토,일        기아   down